
version: "3"

services:

  db:
    image: rethinkdb:2.3
    volumes:
      - "./data:/data"  

  server:
    build: .
    volumes: 
      - "./tinode/chat:/go/src/github.com/tinode/chat"
      - "./tinode/example-react-js:/web/example-react-js"
    depends_on: 
      - db
    ports:
      - "6060:6060"